[package]
name = "paper_server"
version = "1.4.6"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.1" }
paper_cache = { git = "ssh://git@github.com/Paper-Book/paper-cache.git", tag = "v1.5.6" }
byteorder = "1.5.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.10.1" }
thiserror = "1.0.64"
log4rs = "1.3.0"
log = "0.4.22"
nohash-hasher = "0.2.0"
parse-size = "1.1.0"
serde_yaml = "0.9.34"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
bytes = "1.7.2"
typesize = "0.1.9"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6", features = ["background_threads"] }

[[bin]]
name = "paper-server"
path = "src/main.rs"
