[package]
name = "paper_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", version = "0.1.0" }
paper_cache = { git = "ssh://git@github.com/Paper-Book/paper-cache.git", version = "1.0.5" }
byteorder = "1.4.3"
kwik = { git = "https://github.com/KiaShakiba/kwik-rs.git", version = "0.1.0" }
thiserror = "1.0.56"
log4rs = "1.2.0"
log = "0.4.20"
nohash-hasher = "0.2.0"
parse-size = "1.0.0"
