[package]
name = "paper_server"
version = "1.2.10"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.1.1" }
paper_cache = { git = "ssh://git@github.com/Paper-Book/paper-cache.git", tag = "v1.3.4" }
byteorder = "1.5.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.7.0" }
thiserror = "1.0.61"
log4rs = "1.3.0"
log = "0.4.21"
nohash-hasher = "0.2.0"
parse-size = "1.0.0"
serde_yaml = "0.9.34"
dotenv = "0.15.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", features = ["background_threads"] }

[[bin]]
name = "paper-server"
path = "src/main.rs"
