[package]
name = "paper_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
clap = { version = "4.2.7", features = ["derive"] }
paper_core = { git = "ssh://git@github.com/Paper-Book/paper-core.git", version = "0.1.0" }
paper_cache = { git = "ssh://git@github.com/Paper-Book/paper-cache.git", version = "0.1.0" }
