[package]
name = "paper_server"
version = "1.4.14"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.1" }
paper_cache = { git = "ssh://git@github.com/Paper-Book/paper-cache.git", tag = "v1.5.12" }
byteorder = "1.5.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.11.6" }
thiserror = "1.0.65"
log4rs = "1.3.0"
log = "0.4.22"
nohash-hasher = "0.2.0"
parse-size = "1.1.0"
dotenv = "0.15.0"
serde_yml = "0.0.12"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6", features = ["background_threads"] }

[[bin]]
name = "paper-server"
path = "src/main.rs"
